name: CI

on:
  push:
    branches:
      - main
      - "v*"
  pull_request: {}
  release:
    types: [published]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.14.x, 1.21.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}

      - name: Install Dependencies
        run: go mod download

      - name: Tests
        run: go test -v ./...
